### ISSUE TITLE
List of functions not found

### ISSUE THREAD

**Issue by arquinn** [paivaspol/EECS583#2]
Just pushed a commit that has data for bzip. The valgrind_output folder will contain files with <benchmark>.data.results and <benchmark>.instructions.results. These files will be new line separated with the following format: 
<path_to_function_source> <cache_performance>

A list of functions not found will be at valgrind_output/bzip.not.found, and will have the format of 
<filename>: <function_name>

does that work vaspol?

**Comment by arquinn** [comment]
apparently github removed all of my comments surrounded in '<'... so, lets try again! 

Just pushed a commit that has data for bzip. The valgrind_output folder will contain files with [benchmark].data.results and [benchmark].instructions.results. These files will be new line separated with the following format: 
[path_to_function_source][cache_performance]

A list of functions not found will be at valgrind_output/bzip.not.found, and will have the format of 

does that work vaspol?

**Comment by arquinn** [comment]
sorry for the brain dump... note that right now I'm showing cache miss rate, so 0 is good, 100 is bad. Two other things: 
1. We have HIGHLY skewed data... right now we have 39ish examples for bzip, and we have 30 examples that come in at the 0 bin... Spec might be too good! 
2. In the current dataset (without the missing functions), we don't have any examples with non 0 miss rate

**Comment by paivaspol** [comment]
Yep. Got it. I'll get those functions in by tomorrow. Thanks!

**Comment by arquinn** [comment]
90% of them were caught, but there still seems to be a very small subset of the functions that were not caught. They might be in there and I just can't parse them correctly, but I grepped around and didn't see them... 

blocksort.c : mainGtU
bzlib.c : handle_compress.isra.2
compress.c : bsW
bzip2.c : uncompressStream
bzip2.c : compressStream
bzlib.c : BZ2_bzReadOpen
bzlib.c : BZ2_bzWriteOpen

**Comment by paivaspol** [comment]
- `mainGtU` is already in `3.txt` under `blocksort_c`
- `bsW` is in `2.txt` under `compress_c`

The rest aren't there. I'll get those and re-push.

**Comment by paivaspol** [comment]
@arquinn I just extracted those and pushed to #4 The only missing function is `handle_compress.isra.2` which I can't find even in the original source. Let me know if others are still missing. If it looks good, feel free to merge it to master. :)
